import {
  accessoriesImg1,
  accessoriesImg2,
  accessoriesImg3,
  accessoriesImg4,
  brand_samsung,
  brand_apple,
  brand_asus,
  brand_realme,
  brand_lenovo,
  smartphoneImg_1_1,
  smartphoneImg_1_2,
  smartphoneImg_1_3,
  smartphoneImg_1_4,
  smartphoneImg_2_1,
  smartphoneImg_2_2,
  smartphoneImg_2_3,
  smartphoneImg_2_4,
  smartphoneImg_3_1,
  smartphoneImg_3_2,
  smartphoneImg_3_3,
  smartphoneImg_3_4,
  smartphoneImg_4_1,
  smartphoneImg_4_2,
  smartphoneImg_4_3,
  smartphoneImg_4_4,
  laptopImg_1_1,
  laptopImg_1_2,
  laptopImg_1_3,
  laptopImg_1_4,
  laptopImg_2_1,
  laptopImg_2_2,
  laptopImg_2_3,
  laptopImg_2_4,
  laptopImg_3_1,
  laptopImg_3_2,
  laptopImg_3_3,
  laptopImg_3_4,
  laptopImg_4_1,
  laptopImg_4_2,
  laptopImg_4_3,
} from '@/assets/constants';

export const smartphoneData = [
  {
    id: 1,
    name: 'Apple iPhone 15 Pro Max 256Gb',
    href: 'apple-iphone-15-pro-max-256gb',
    category: 'smartphones',
    images: [
      { link: smartphoneImg_1_1, order: 0 },
      { link: smartphoneImg_1_2, order: 1 },
      { link: smartphoneImg_1_3, order: 2 },
      { link: smartphoneImg_1_4, order: 3 },
    ],
    price: '32 900',
    code: '984561',
    rate: 5,
    anotherColors: ['#ffffff', '#004DFF', '#808080'],
    isLiked: false,
  },
  {
    id: 2,
    name: 'Samsung Galaxy A24 6/128Gb Black',
    href: 'Samsung-Galaxy-A24-6-128Gb-Black',
    category: 'smartphones',
    images: [
      { link: smartphoneImg_2_1, order: 0 },
      { link: smartphoneImg_2_2, order: 1 },
      { link: smartphoneImg_2_3, order: 2 },
      { link: smartphoneImg_2_4, order: 3 },
    ],
    price: '19 900',
    code: '984561',
    rate: 5,
    anotherColors: ['#ffffff', '#004DFF', '#808080'],
    isLiked: false,
  },
  {
    id: 3,
    name: 'Samsung Galaxy S24 Ultra 12/512Gb',
    href: 'samsung-galaxy-s24-ultra-12-512gb',
    category: 'smartphones',
    images: [
      { link: smartphoneImg_3_1, order: 0 },
      { link: smartphoneImg_3_2, order: 1 },
      { link: smartphoneImg_3_3, order: 2 },
      { link: smartphoneImg_3_4, order: 3 },
    ],
    price: '62 900',
    code: '784664',
    rate: 5,
    anotherColors: ['#8B00FF', '#1C1817', '#FFFF00', '#808080'],
    isLiked: false,
  },
  {
    id: 4,
    name: 'Apple iPhone 15 Pro 128 Gb Blue Titanium',
    href: 'apple-iphone-15-128gb-blue',
    category: 'smartphones',
    images: [
      { link: smartphoneImg_4_1, order: 0 },
      { link: smartphoneImg_4_2, order: 1 },
      { link: smartphoneImg_4_3, order: 2 },
      { link: smartphoneImg_4_4, order: 3 },
    ],
    price: '43 600',
    code: '456158',
    rate: 5,
    anotherColors: ['#FFFF00', '#00820D', '#1C1817', '#FFCBDB', '#00BFFF'],
    isLiked: false,
  },
];

export const laptopData = [
  {
    id: 5,
    name: 'Apple MacBook Air 13.6 M3 8GB 256GB',
    href: 'apple-macbook-air-13.6-m3-8gb-256gb',
    category: 'laptops',
    images: [
      { link: laptopImg_1_1, order: 0 },
      { link: laptopImg_1_2, order: 1 },
      { link: laptopImg_1_3, order: 2 },
      { link: laptopImg_1_4, order: 3 },
    ],
    price: '59 490',
    code: '847687',
    rate: 5,
    anotherColors: ['#1C1817', '#F5F5DC', '#808080'],
    isLiked: false,
  },
  {
    id: 6,
    name: 'Lenovo IdeaPad 1 15ALC7',
    href: 'lenovo-ideapad-1-15alc7',
    category: 'laptops',
    images: [
      { link: laptopImg_2_1, order: 0 },
      { link: laptopImg_2_2, order: 1 },
      { link: laptopImg_2_3, order: 2 },
      { link: laptopImg_2_4, order: 3 },
    ],
    price: '16 999',
    code: '256462',
    rate: 5,
    anotherColors: ['#808080'],
    isLiked: false,
  },
  {
    id: 7,
    name: 'Asus TUF Gaming A15',
    href: 'asus-tuf-gaming-a15',
    category: 'laptops',
    images: [
      { link: laptopImg_3_1, order: 0 },
      { link: laptopImg_3_2, order: 1 },
      { link: laptopImg_3_3, order: 2 },
      { link: laptopImg_3_4, order: 3 },
    ],
    price: '32 900',
    code: '458688',
    rate: 5,
    anotherColors: ['#1C1817'],
    isLiked: false,
  },
  {
    id: 8,
    name: 'Apple MacBook Air 15.3 M3 8GB 256GB',
    href: 'apple-macbook-air-15.3-m3-8gb-256gb',
    category: 'laptops',
    images: [
      { link: laptopImg_4_1, order: 0 },
      { link: laptopImg_4_2, order: 1 },
      { link: laptopImg_4_3, order: 2 },
    ],
    price: '61 999',
    code: '594898',
    rate: 5,
    anotherColors: ['#1C1817', '#F5F5DC', '#808080', '#1C1817'],
    isLiked: false,
  },
];

export const brandData = [
  {
    id: 1,
    img: brand_samsung,
  },
  {
    id: 2,
    img: brand_apple,
  },
  {
    id: 3,
    img: brand_asus,
  },
  {
    id: 4,
    img: brand_realme,
  },
  {
    id: 5,
    img: brand_lenovo,
  },
];

export const productAccessoriesData = [
  {
    id: 1,
    name: 'iPhone 15 Pro Silicone Case with MagSafe',
    images: [{link: accessoriesImg1, order: 0}],
    anotherColors: [],
    isLiked: false,
    rate: 5,
    price: '2 799',
    code: '874364',
    category: 'smartphones',
  },
  {
    id: 2,
    name: 'iPhone 15 Pro Silicone Case with MagSafe',
    images: [{link: accessoriesImg2, order: 0}],
    anotherColors: [],
    isLiked: false,
    rate: 5,
    price: '2 799',
    code: '875496',
    category: 'smartphones',
  },
  {
    id: 3,
    name: 'iPhone 15 Pro Silicone Case with MagSafe',
    images: [{link: accessoriesImg3, order: 0}],
    anotherColors: ['#FFFF00', '#00820D', '#1C1817', '#FFCBDB', '#00BFFF'],
    isLiked: false,
    rate: 5,
    price: '2 799',
    code: '456158',
    category: 'smartphones',
  },
  {
    id: 4,
    name: 'iPhone 15 Pro Silicone Case with MagSafe',
    images: [{link: accessoriesImg4, order: 0}],
    anotherColors: ['#ffffff', '#00BFFF', '#3EB489', '#FFCBDB', '#C8A2C8'],
    isLiked: false,
    rate: 5,
    price: '2 799',
    code: '557769',
    category: 'smartphones',
  },
  {
    id: 5,
    name: 'iPhone 15 Pro Silicone Case with MagSafe',
    images: [{link: accessoriesImg2, order: 0}],
    anotherColors: ['#000', '#d84f34', '#236aed', '#FFCBDB', '#C8A2C8'],
    isLiked: false,
    rate: 3,
    price: '3 199',
    code: '173497',
    category: 'smartphones',
  },
  {
    name: 'iPhone 15 Pro Silicone Case with MagSafe',
    images: [{link: accessoriesImg4, order: 0}],
    anotherColors: [],
    isLiked: false,
    rate: 4,
    price: '2 835',
    code: '157781',
    category: 'smartphones',
  },
];

export const previouslyReviewedData = [
  {
    id: 7,
    name: 'Asus TUF Gaming A15',
    href: 'asus-tuf-gaming-a15',
    category: 'laptops',
    images: [
      { link: laptopImg_3_1, order: 0 },
      { link: laptopImg_3_2, order: 1 },
      { link: laptopImg_3_3, order: 2 },
    ],
    price: '32 900',
    code: '458688',
    rate: 5,
    anotherColors: ['#1C1817'],
    isLiked: false,
  },
  {
    id: 8,
    name: 'Apple MacBook Air 15.3 M3 8GB 256GB',
    href: 'apple-macbook-air-15.3-m3-8gb-256gb',
    category: 'laptops',
    images: [
      { link: laptopImg_4_1, order: 0 },
      { link: laptopImg_4_2, order: 1 },
      { link: laptopImg_4_3, order: 2 },
    ],
    price: '61 999',
    code: '594898',
    rate: 5,
    anotherColors: ['#1C1817', '#F5F5DC', '#808080', '#1C1817'],
    isLiked: false,
  },
  {
    id: 2,
    name: 'Samsung Galaxy A24 6/128Gb Black',
    href: 'Samsung-Galaxy-A24-6-128Gb-Black',
    category: 'smartphones',
    images: [
      { link: smartphoneImg_2_1, order: 0 },
      { link: smartphoneImg_2_2, order: 1 },
      { link: smartphoneImg_2_3, order: 2 },
      { link: smartphoneImg_2_4, order: 3 },
    ],
    price: '19 900',
    code: '984561',
    rate: 5,
    anotherColors: ['#ffffff', '#004DFF', '#808080'],
    isLiked: false,
  },
  {
    id: 4,
    name: 'Apple iPhone 15 Pro 128 Gb Blue Titanium',
    href: 'apple-iphone-15-128gb-blue',
    category: 'smartphones',
    images: [
      { link: smartphoneImg_4_1, order: 0 },
      { link: smartphoneImg_4_2, order: 1 },
      { link: smartphoneImg_4_3, order: 2 },
      { link: smartphoneImg_4_4, order: 3 },
    ],
    price: '43 600',
    code: '456158',
    rate: 5,
    anotherColors: ['#FFFF00', '#00820D', '#1C1817', '#FFCBDB', '#00BFFF'],
    isLiked: false,
  },
];
