import {
  accessoriesImg1,
  accessoriesImg2,
  accessoriesImg3,
  accessoriesImg4,
  smartphoneImg_1,
  smartphoneImg_2,
  smartphoneImg_3,
  smartphoneImg_4,
  brand_samsung,
  brand_apple,
  brand_asus,
  brand_realme,
  brand_lenovo,
  laptopImg_1,
  laptopImg_2,
  laptopImg_3,
  laptopImg_4,
  previouslyViewed_1,
  previouslyViewed_2,
  previouslyViewed_3,
} from '@/assets/constants';

export const smartphoneData = [
  {
    id: 1,
    title: 'Samsung Galaxy A24 6/128Gb Black',
    href: 'samsung-galaxy-a24-6-128gb-black',
    category: 'Smartphone',
    img: smartphoneImg_1,
    price: '19 900',
    code: '456158',
    rate: 5,
    anotherColors: ['#00820D', '#8B0000', '#1C1817'],
    isLiked: false,
  },
  {
    id: 2,
    title: 'Apple iPhone 15 Pro Max 256Gb ',
    href: 'apple-iphone-15-pro-max-256gb',
    category: 'Smartphone',
    img: smartphoneImg_2,
    price: '32 900',
    code: '984561',
    rate: 5,
    anotherColors: ['#ffffff', '#004DFF', '#808080'],
    isLiked: false,
  },
  {
    id: 3,
    title: 'Samsung Galaxy S24 Ultra 12/512Gb',
    href: 'samsung-galaxy-s24-ultra-12-512gb',
    category: 'Smartphone',
    img: smartphoneImg_3,
    price: '62 900',
    code: '784664',
    rate: 5,
    anotherColors: ['#8B00FF', '#1C1817', '#FFFF00', '#808080'],
    isLiked: false,
  },
  {
    id: 4,
    title: 'Apple iPhone 15 128Gb Blue',
    href: 'apple-iphone-15-128gb-blue',
    category: 'Smartphone',
    img: smartphoneImg_4,
    price: '39 999',
    code: '456158',
    rate: 5,
    anotherColors: ['#FFFF00', '#00820D', '#1C1817', '#FFCBDB', '#00BFFF'],
    isLiked: false,
  },
];

export const laptopData = [
  {
    id: 5,
    title: 'Apple MacBook Air 13.6 M3 8GB 256GB',
    href: 'apple-macbook-air-13.6-m3-8gb-256gb',
    category: 'Laptop',
    img: laptopImg_1,
    price: '59 490',
    code: '847687',
    rate: 5,
    anotherColors: ['#1C1817', '#F5F5DC', '#808080'],
    isLiked: false,
  },
  {
    id: 6,
    title: 'Lenovo IdeaPad 1 15ALC7',
    href: 'lenovo-ideapad-1-15alc7',
    category: 'Laptop',
    img: laptopImg_2,
    price: '16 999',
    code: '256462',
    rate: 5,
    anotherColors: ['#808080'],
    isLiked: false,
  },
  {
    id: 7,
    title: 'Asus TUF Gaming A15',
    href: 'asus-tuf-gaming-a15',
    category: 'Laptop',
    img: laptopImg_3,
    price: '32 900',
    code: '458688',
    rate: 5,
    anotherColors: ['#1C1817'],
    isLiked: false,
  },
  {
    id: 8,
    title: 'Apple MacBook Air 15.3 M3 8GB 256GB',
    href: 'apple-macbook-air-15.3-m3-8gb-256gb',
    category: 'Laptop',
    img: laptopImg_4,
    price: '61 999',
    code: '594898',
    rate: 5,
    anotherColors: ['#1C1817', '#F5F5DC', '#808080', '#1C1817'],
    isLiked: false,
  },
];

export const brandData = [
  {
    id: 1,
    img: brand_samsung,
  },
  {
    id: 2,
    img: brand_apple,
  },
  {
    id: 3,
    img: brand_asus,
  },
  {
    id: 4,
    img: brand_realme,
  },
  {
    id: 5,
    img: brand_lenovo,
  },
];

export const productAccessoriesData = [
  {
    id: 1,
    title: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: accessoriesImg1,
    anotherColors: [],
    isLiked: false,
    rate: 5,
    price: '2 799',
    code: '874364',
    category: 'smartphone'
  },
  {
    id: 2,
    title: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: accessoriesImg2,
    anotherColors: [],
    isLiked: false,
    rate: 5,
    price: '2 799',
    code: '875496',
    category: 'smartphone'
  },
  {
    id: 3,
    title: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: accessoriesImg3,
    anotherColors: ['#FFFF00', '#00820D', '#1C1817', '#FFCBDB', '#00BFFF'],
    isLiked: false,
    rate: 5,
    price: '2 799',
    code: '456158',
    category: 'smartphone'
  },
  {
    id: 4,
    title: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: accessoriesImg4,
    anotherColors: ['#ffffff', '#00BFFF', '#3EB489', '#FFCBDB', '#C8A2C8'],
    isLiked: false,
    rate: 5,
    price: '2 799',
    code: '557769',
    category: 'smartphone'
  },
  {
    id: 5,
    title: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: accessoriesImg2,
    anotherColors: ['#000', '#d84f34', '#236aed', '#FFCBDB', '#C8A2C8'],
    isLiked: false,
    rate: 3,
    price: '3 199',
    code: '173497',
    category: 'smartphone'
  },
  {
    id: 6,
    title: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: accessoriesImg4,
    anotherColors: [],
    isLiked: false,
    rate: 4,
    price: '2 835',
    code: '157781',
    category: 'smartphone'
  },
];

export const previouslyReviewedData = [
  {
    id: 1,
    title: 'Canon RF 24-70mm f/2.8 L IS USM',
    img: previouslyViewed_1,
    price: '95 999',
    code: '874364',
    rate: 5,
    anotherColors: [],
    isLiked: false,
  },
  {
    id: 2,
    title: 'Canon EOS 4000D 18-55 DC III',
    img: previouslyViewed_2,
    price: '16 699',
    code: '875496',
    rate: 5,
    anotherColors: [],
    isLiked: false,
  },
  {
    id: 3,
    title: 'Apple iPhone 15 128Gb Blue',
    img: smartphoneImg_4,
    price: '39 999',
    code: '456158',
    rate: 5,
    anotherColors: ['#FFFF00', '#00820D', '#1C1817', '#FFCBDB', '#00BFFF'],
    isLiked: false,
  },
  {
    id: 4,
    title: 'Fujifilm INSTAX MINI 12 Lilac Purple',
    img: previouslyViewed_3,
    price: '3 900',
    code: '557769',
    rate: 5,
    anotherColors: ['#ffffff', '#00BFFF', '#3EB489', '#FFCBDB', '#C8A2C8'],
    isLiked: false,
  },
];


