import {
  BasketIcon,
  accessoriesImg1,
  accessoriesImg2,
  accessoriesImg3,
  accessoriesImg4,
  laptopImg_1_1,
  laptopImg_2_1,
  laptopImg_3_1,
  laptopImg_4_1,
  previouslyViewedImg_1_1,
  previouslyViewedImg_2_1,
  previouslyViewedImg_3_1,
} from '@/assets/constants';
import { IProduct } from '@/interfaces/interfaces';

export const filters = {
  'categories': ['Smartphones', 'Laptops', 'Tablets'],
  'brands': [
    'Apple',
    'Samsung',
    'Lenovo',
    'Asus',
    'Nikon',
    'Fujifilm',
    'Canon',
    'JBL',
    'Dell',
  ],
  'builtInMemory': [
    '128 GB',
    '256 GB',
    '512 GB and more',
  ],
  // 'rams': ['4 Gb', '6 Gb', '8 Gb', '12 Gb', '16 Gb'],
  // 'fleshCard': ['No', 'Yes'],
  // 'colors': [
  //   'WHITE',
  //   'BLACK',
  //   'RED',
  //   'GREEN',
  //   'BLUE',
  //   'VIOLET',
  //   'GREY',
  //   'GOLD',
  //   'ORANGE',
  //   'PINK',
  // ],
  // 'colorsHex': [
  //   '#FFFFFF',
  //   '#000000',
  //   '#FF0000',
  //   '#008000',
  //   '#0000FF',
  //   '#800080',
  //   '#808080 ',
  //   '#FFD700',
  //   '#FFA500',
  //   '#FFC0CB',
  // ],
  // 'cores': ['8 Cores', '4 Cores', '6 Cores', '10 Cores', '4+4 Cores'],
  // 'screens': [
  //   '2796x1290 pixels',
  //   '1080x2340 pixels',
  //   '1440x3120 pixels',
  //   '1080x2350 pixels',
  //   '2556x1179 pixels',
  //   '2532x1170 pixels',
  //   '2388x1668 pixels',
  //   '2560x1600 pixels',
  //   '1920x1080 pixels',
  //   '2880x1864 pixels',
  // ],
  // 'images': [
  //   { link: smartphoneImg_1_1, order: 1 },
  //   { link: smartphoneImg_2_1, order: 2 },
  //   { link: smartphoneImg_3_1, order: 3 },
  //   { link: smartphoneImg_4_1, order: 4 },
  // ],
};

export const smartData: IProduct[] = [
  {
    id: 1,
    name: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: [accessoriesImg1],
    basketIcon: BasketIcon,
    anotherColors: [],
    isLiked: false,
    rate: 5,
    popular: 6,
    price: 2799,
    brand: 'Apple',
    ram: 8,
    builtInMemory: 32,
    code: '874364',
    category: 'smartphone',
    cameraMP: 15,
  },
  {
    id: 2,
    name: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: [accessoriesImg2],
    basketIcon: BasketIcon,
    anotherColors: [],
    isLiked: false,
    rate: 4,
    popular: 7,
    price: 799,
    brand: 'Apple',
    ram: 8,
    builtInMemory: 128, // ГБ встроенной памяти
    code: '875496',
    category: 'smartphone',
    cameraMP: 15,
  },
  {
    id: 3,
    name: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: [accessoriesImg3],
    basketIcon: BasketIcon,
    anotherColors: ['#FFFF00', '#00820D', '#1C1817', '#FFCBDB', '#00BFFF'],
    isLiked: false,
    rate: 3,
    popular: 8,
    price: 5799,
    brand: 'Apple',
    ram: 8,
    builtInMemory: 32,
    code: '456158',
    category: 'smartphone',
    cameraMP: 45,
  },
  {
    id: 4,
    name: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: [accessoriesImg4],
    basketIcon: BasketIcon,
    anotherColors: ['#ffffff', '#00BFFF', '#3EB489', '#FFCBDB', '#C8A2C8'],
    isLiked: false,
    rate: 2,
    popular: 8,
    price: 6799,
    brand: 'Apple',
    ram: 8,
    builtInMemory: 32,
    code: '557769',
    category: 'smartphone',
    cameraMP: 45,
  },
  {
    id: 5,
    name: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: [accessoriesImg2],
    basketIcon: BasketIcon,
    anotherColors: ['#000', '#d84f34', '#236aed', '#FFCBDB', '#C8A2C8'],
    isLiked: false,
    rate: 3,
    popular: 4,
    price: 7199,
    brand: 'Apple',
    ram: 8,
    builtInMemory: 128,
    code: '173497',
    category: 'smartphone',
    cameraMP: 25,
  },
  {
    id: 6,
    name: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: [accessoriesImg4],
    basketIcon: BasketIcon,
    anotherColors: [],
    isLiked: false,
    rate: 4,
    popular: 5,
    price: 8835,
    brand: 'Apple',
    ram: 8,
    builtInMemory: 128,
    code: '157781',
    category: 'smartphone',
    cameraMP: 15,
  },
];

export const productsData = [
  {
    id: 1,
    title: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: accessoriesImg1,
    basketIcon: BasketIcon,
    anotherColors: [],
    isLiked: false,
    rate: 5,
    price: '2 799 ₴',
    brand: 'Apple',
    ram: 8, // ГБ оперативной памяти
    builtInMemory: 128, // ГБ встроенной памяти
    code: '874364',
    category: 'smartphone',
    cameraMP: 15,
  },
  {
    id: 2,
    title: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: accessoriesImg2,
    basketIcon: BasketIcon,
    anotherColors: [],
    isLiked: false,
    rate: 5,
    price: '2 799 ₴',
    brand: 'Apple',
    ram: 8, // ГБ оперативной памяти
    builtInMemory: 128, // ГБ встроенной памяти
    code: '875496',
    category: 'smartphone',
    cameraMP: 15,
  },
  {
    id: 3,
    title: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: accessoriesImg3,
    basketIcon: BasketIcon,
    anotherColors: ['#FFFF00', '#00820D', '#1C1817', '#FFCBDB', '#00BFFF'],
    isLiked: false,
    rate: 5,
    price: '2 799 ₴',
    brand: 'Apple',
    ram: 8, // ГБ оперативной памяти
    builtInMemory: 128, // ГБ встроенной памяти
    code: '456158',
    category: 'smartphone',
    cameraMP: 15,
  },
  {
    id: 4,
    title: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: accessoriesImg4,
    basketIcon: BasketIcon,
    anotherColors: ['#ffffff', '#00BFFF', '#3EB489', '#FFCBDB', '#C8A2C8'],
    isLiked: false,
    rate: 5,
    price: '2 799 ₴',
    code: '557769',
    category: 'smartphone',
    cameraMP: 15,
  },
  {
    id: 5,
    title: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: accessoriesImg2,
    basketIcon: BasketIcon,
    anotherColors: ['#000', '#d84f34', '#236aed', '#FFCBDB', '#C8A2C8'],
    isLiked: false,
    rate: 3,
    price: '3 199 ₴',
    brand: 'Apple',
    ram: 8, // ГБ оперативной памяти
    builtInMemory: 128, // ГБ встроенной памяти
    code: '173497',
    category: 'smartphone',
    cameraMP: 15,
  },
  {
    id: 6,
    title: 'iPhone 15 Pro Silicone Case with MagSafe',
    img: accessoriesImg4,

    basketIcon: BasketIcon,
    anotherColors: [],
    isLiked: false,
    rate: 4,
    price: '2 835 ₴',
    brand: 'Apple',
    ram: 8, // ГБ оперативной памяти
    builtInMemory: 128, // ГБ встроенной памяти
    code: '157781',
    category: 'smartphone',
    cameraMP: 15,
  },
  {
    id: 7,
    title: 'Apple MacBook Air 13.6 M3 8GB 256GB',
    img: laptopImg_1_1,
    price: '59 490 ₴',
    code: '847687',
    rate: 5,
    anotherColors: ['#1C1817', '#F5F5DC', '#808080'],
    isLiked: false,
    category: 'laptop',
  },
  {
    id: 8,
    title: 'Lenovo IdeaPad 1 15ALC7',
    img: laptopImg_2_1,
    price: '16 999 ₴',
    code: '256462',
    rate: 5,
    anotherColors: ['#808080'],
    isLiked: false,
    category: 'laptop',
  },
  {
    id: 9,
    title: 'Asus TUF Gaming A15',
    img: laptopImg_3_1,
    price: '32 900 ₴',
    code: '458688',
    rate: 5,
    anotherColors: ['#1C1817'],
    isLiked: false,
    category: 'laptop',
  },
  {
    id: 10,
    title: 'Apple MacBook Air 15.3 M3 8GB 256GB',
    img: laptopImg_4_1,
    price: '61 999 ₴',
    code: '594898',
    rate: 5,
    anotherColors: ['#1C1817', '#F5F5DC', '#808080', '#1C1817'],
    isLiked: false,
    category: 'laptop',
  },
  {
    id: 11,
    title: 'Canon RF 24-70mm f/2.8 L IS USM',
    img: previouslyViewedImg_1_1,
    price: '95 999 ₴',
    code: '874364',
    rate: 5,
    anotherColors: [],
    isLiked: false,
    category: 'photo',
  },
  {
    id: 12,
    title: 'Canon EOS 4000D 18-55 DC III',
    img: previouslyViewedImg_2_1,
    price: '16 699 ₴',
    code: '875496',
    rate: 5,
    anotherColors: [],
    isLiked: false,
    category: 'photo',
  },
  {
    id: 14,
    title: 'Fujifilm INSTAX MINI 12 Lilac Purple',
    img: previouslyViewedImg_3_1,
    price: '3 900 ₴',
    code: '557769',
    rate: 5,
    anotherColors: ['#ffffff', '#00BFFF', '#3EB489', '#FFCBDB', '#C8A2C8'],
    isLiked: false,
    category: 'photo',
  },
];
